#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  export BROWSER="/usr/bin/open"

   # export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
   #export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
   # export PATH="/usr/local/opt/texinfo/bin:$PATH"
   # export PATH="/usr/local/opt/gettext/bin:$PATH"
   # # export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

  #export NODE_PATH=/usr/local/opt/node@8
  # export PATH=/usr/local/bin:/usr/local/lib:/usr/bin:/bin
  export PATH=/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gettext/bin:/usr/local/opt/texinfo/bin:/usr/local/lib:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/local/bin

  export MANPATH="/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH"

  export KERL_CONFIGURE_OPTIONS="--disable-debug --disable-silent-rules --without-javac --enable-shared-zlib --enable-dynamic-ssl-lib --enable-hipe --enable-sctp --enable-smp-support --enable-threads --enable-kernel-poll --enable-wx --enable-darwin-64bit --with-ssl=/usr/local/Cellar/openssl/1.0.2p"


  #fzf
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

  # flutter
  export PATH=$HOME/projects/sdk/flutter/bin:$PATH

  # pyenv
  # export PYENV_ROOT="$HOME/.pyenv"
  # export PATH="$PYENV_ROOT/bin:$PATH"

  # eval "$(pyenv init -)"

  . $HOME/.asdf/asdf.sh
  . $HOME/.asdf/completions/asdf.bash
fi


